service:
  name: zenklub-slots-manager

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  createSlot:
    handler: handlers/slot/create.create
    events:
      - http:
          path: slot
          method: post
          cors: true

  createAgenda:
    handler: handlers/agenda/create.create
    events:
      - http:
          path: agenda/{professionalId}
          method: post
          cors: true

  getSlot:
    handler: handlers/slot/get.get
    events:
      - http:
          path: slot/{id}
          method: get
          cors: true

  listSlots:
    handler: handlers/slot/list.list
    events:
      - http:
          path: slot
          method: get
          cors: true

  bookSlot:
    handler: handlers/agenda/book.book
    events:
      - http:
          path: agenda/{professionalId}/book/{timeId}
          method: put
          cors: true

  deleteSlot:
    handler: handlers/slot/delete.remove
    events:
      - http:
          path: slot/{id}
          method: delete
          cors: true

  createProfessional:
    handler: handlers/professional/create.create
    events:
      - http:
          path: professional
          method: post
          cors: true

  getProfessional:
    handler: handlers/professional/get.get
    events:
      - http:
          path: professional/{id}
          method: get
          cors: true

  updateProfessional:
    handler: handlers/professional/update.update
    events:
      - http:
          path: professional/{id}
          method: put
          cors: true

  listProfessional:
    handler: handlers/professional/list.list
    events:
      - http:
          path: professional
          method: get
          cors: true

  deleteProfessional:
    handler: handlers/professional/delete.remove
    events:
      - http:
          path: professional/{id}
          method: delete
          cors: true

