module.exports = {
  PROFESSIONAL_REQUIRED: 'MONGOOSE ERROR NOT IMPLEMENTED',
  HOUR_REQUIRED: 'MONGOOSE ERROR NOT IMPLEMENTED',
  MINUTES_REQUIRED: 'MONGOOSE ERROR NOT IMPLEMENTED',
  WEEKDAY_REQUIRED: 'MONGOOSE ERROR NOT IMPLEMENTED',
  MONTH_REQUIRED: 'MONGOOSE ERROR NOT IMPLEMENTED',
  DATE_REQUIRED: 'MONGOOSE ERROR NOT IMPLEMENTED',
};
